### ISSUE TITLE
Party-information: Improve, make consistent

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#106]
We should let our attendees know about all parties they are invited to.
* Reject Closing / JSconf Opening Party on Thursday 8pm (Crack Bellmer)
* CSSconf Opening / JSconf Party on Friday 9pm (Radialsystem)
* CSSconf Closing Party on Saturday 9pm (Radialsystem)
* JSconf Closing Party on Sunday 7:30pm (Hoppetosse)
* relax.js Brunch on Monday 10am (Datscha)

**Comment by Kriesse** [comment]
This should also mention that tickets to the party can be purchased…
“This ticket gives you access to the CSSconf Party on Saturday, September 22nd, 9pm, at Radialsystem V. If you already have a ticket to CSSconf EU, JSconf EU, or Reject JS, you don't need a Party Ticket, access to the party is already included.”
Ticket link for the CSSconf EU party, Saturday: 
https://ti.to/cssconfeu/cssconf-eu-2015

Ticket Link for the JSconf EU party, Friday:
https://ti.to/jsconfeu/jsconf-eu-2015

**Comment by retrospekt** [comment]
I've added the above information and links to the info page, please deploy!

We will also include this in the Newsletter to our attendees. The "Party" item on the Schedule already points to the section on the Info page.

If this information needs to go anywhere else, please let me know!
