### ISSUE TITLE
Animation ideas

### ISSUE THREAD

**Issue by verpixelt** [cssconf/2015.cssconf.eu#56]
I would like to collect ideas which elements on the page we could animate.

This is the first one I have in mind (dotted line shows the path of the animation).
![animation](https://cloud.githubusercontent.com/assets/1640079/7232590/c7a6ca36-e77c-11e4-92dc-933b850e66d6.png)
Ideally the circles get bigger if the viewing distance is shorter.

**Comment by Kriesse** [comment]
Pinging all the animation wizards –
@verpixelt @rendro @sfrdmn @usefulthink @Lucie-H @lewiscowper  

Adding fancy animations to the site is obviously a nice-to-have feature, and should not block more important issues. But if anyone is burning to implement these ideas (or something else), please start a branch and go crazy :) Happy to help and review stuff.

I wonder if we could even find help in the CSSclasses crowd? There were some people really into animation? What do you think, should we reach out?
