### ISSUE TITLE
Implement Blog Improvements

### ISSUE THREAD

**Issue by verpixelt** [cssconf/2015.cssconf.eu#82]
- [x] Design approval from organizers
- [x] Implementation

**Comment by verpixelt** [comment]
**Feedback:**
The new added elements are too big in comparison with the rest of the page. We like the over all look, though. Please start with development as soon as possible.
@usefulthink If you have any question regarding the repos or setup, please ping me directly in Slack.
____
![cssconf2015-blog-post](https://cloud.githubusercontent.com/assets/1640079/8734458/68054102-2c0a-11e5-92ea-3f342049d683.jpg)
![cssconf2015-blog](https://cloud.githubusercontent.com/assets/1640079/8734462/6d07ae24-2c0a-11e5-8e85-d69b9d4205f4.jpg)

**Comment by verpixelt** [comment]
Status: Most of the stuff is already built. I'll try to fix the last issues tonight/tomorrow.

**Comment by usefulthink** [comment]
should we move blog-related issues to https://github.com/cssconf/blog-server?

**Comment by Kriesse** [comment]
done :)
