### ISSUE TITLE
Design and implement "Sold Out" Badge

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#86]
We expect to sell out on Tuesday :)
Would be good to have a subtle, visible little badge (ribbon, subline, banner…)  that says "Regular Tickets Sold Out", on the start page and maybe in the top bar?
@RalloTubbs Any ideas?

**Comment by RalloTubbs** [comment]
Have an idea, will do it today in the evening

**Comment by RalloTubbs** [comment]
![booked_up](https://cloud.githubusercontent.com/assets/7797904/9306539/4ed3d308-44f9-11e5-8188-d58bfa0ad39e.png)

**Comment by verpixelt** [comment]
@lewiscowper could you please implement that with the following text:
`We've sold out! But don't worry, you can still become a sponsor here.`

**Comment by lewiscowper** [comment]
Just pushed a commit starting this off. It's still massively buggy, breaks the sticky header, and isn't rendered as a closable modal yet. But it's getting there:

![screen shot 2015-08-17 at 19 40 18](https://cloud.githubusercontent.com/assets/593574/9311657/ee0c4b26-4517-11e5-9e66-a81715145826.png)
