### ISSUE TITLE
Blog Post announcing next speakers

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#87]
* [x] create copy
* [x] prepare images
* [x] prepare post
* [x] style images?

Similar to this one, but with images:
http://blog.cssconf.eu/2015/04/21/lea-verou-claudine-sarahe/

cc @usefulthink @verpixelt - can you help with the image styling of the speaker images in blog posts? Do we have a mockup for that yet?

**Comment by Kriesse** [comment]
This post should go live on Monday or Tuesday morning, before the last ticket sale.

**Comment by verpixelt** [comment]
@Kriesse could you please be more specific!? What exactly do you mean with 'styling of the speaker images'?

**Comment by Kriesse** [comment]
As in, provide classes to have a picture of each speaker in a blog post, ideally in the same style as on the homepage. Not sure if that has been added yet, or if a mockup has been provided by @rallotubbs. Low priority — if  we don't have time we can just float an image as in the interview post.



— Kristina

+14157452104 | @kriesse

**Comment by Kriesse** [comment]
closing, we can polish the styling of the images later too.
