### ISSUE TITLE
Build speaker details page

### ISSUE THREAD

**Issue by verpixelt** [cssconf/2015.cssconf.eu#88]
![cssconf2015-speaker-detail](https://cloud.githubusercontent.com/assets/1640079/9021269/6fe9df0e-383a-11e5-9da8-80accca8a064.jpg)

**Comment by verpixelt** [comment]
@usefulthink let's have quick chat about it tomorrow (Sun 2nd Aug) noon and see how we can split up the work.

**Comment by Kriesse** [comment]
This one is becoming urgent, as our MC and sketchnoter are waiting for the speaker detail infos (and attendees as well).

The minimum data on this page should be:

- Speaker Name
- Speaker img
- Speaker Short bio
- Talk Title
- Talk Description
- Speaker links (twitter, website, blog…)
After the conference:
- Talk video (just a link, or embedded)

Let me know what's the status of this issue. If @verpixelt and @usefulthink don't have time at the moment, I can create the structure today, and hand over to @Lucie-H or @lewiscowper to help fill in the date.

**Comment by verpixelt** [comment]
The initial layout states the page is somewhat static and displays all speaker at the bottom of the page. The only "interactive" part would be the top (description of each individual speaker). A easy but super redundant way would be to build a page for each speaker and include the rest of the speakers as "partial". The more elegant (and preferred) solution would be to change the speaker information on click on the same page. I'm not able to build that my own unfortunately.
Best solution would be as stated above + managing the speaker details in a YAML file.
Maybe that isn't to much work to get it done!? /cc @usefulthink

**Comment by frontdevde** [comment]
@verpixelt @usefulthink 

Let's go for the easiest and most pragmatic solution here:

* Speaker detail at the top (content as described by kriesse above)
* Partial below that shows the other speakers but is just links to their individual speaker detail pages

Like @Kriesse at this point we need to have them ready asap, so let's just go for the easiest route. 

@usefulthink Could you pick this one up, please?
