### ISSUE TITLE
Add speakers guide page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#89]
We need a page like this again:
http://2014.cssconf.eu/speakers-guide

A much simpler design is ok. The information is mostly the same and we can copy it over to get started. Only a few details will change. I can help with getting that right once the page is there.

**Comment by verpixelt** [comment]
I've already start with it yesterday. There is a branch for it: https://github.com/cssconf/2015.cssconf.eu/tree/speakers-guide

**Comment by Kriesse** [comment]
Done, closing :+1:
