### ISSUE TITLE
Add more sponsor logos

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#90]
etecture (position after Travis, before Github):
http://www.etecture.de/
http://www.etecture.de/wp-content/uploads/2015/01/etecture-logo.svg (sorry, still needs to be made black/white)

Automattic (position after keyCDN):
https://automattic.com/
logo sent via email

**Comment by verpixelt** [comment]
@Kriesse are they both cool with us using the logos b/w?

**Comment by verpixelt** [comment]
Done.

**Comment by Kriesse** [comment]
Awesome! Automattic sent the b/w one, they're cool. Will check back with etecture.
