### ISSUE TITLE
Add Silke and Martin to team list

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#91]
http://2015.cssconf.eu/team/ :)

**Comment by Lucie-H** [comment]
Wer sind Silke und Martin? ;) (= wo finde ich ihre Nachnamen und welche Aufgabe soll ich eintragen Haben wir dafür ein Google Doc?)

**Comment by verpixelt** [comment]
Martin Schuhfuss - Code - usefulthink
Silke Voigts - Design - @silkine

**Comment by Lucie-H** [comment]
https://github.com/cssconf/2015.cssconf.eu/pull/95

**Comment by verpixelt** [comment]
Merged and pushed to live!
