### ISSUE TITLE
Remove "Buy Ticket" button on info page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#94]
… and add a note that we are sold out. Maybe mention that we'll retweet tickets that people are trying to sell.

**Comment by Lucie-H** [comment]
"For this year, CSSconf EU is SOLD OUT. But we will try to announce via twitter if people have spare tickets to sell." << like this with link to twitter? 
![screen shot 2015-08-17 at 14 19 58](https://cloud.githubusercontent.com/assets/5932926/9304690/144c4098-44eb-11e5-8583-306968c91219.png)

**Comment by verpixelt** [comment]
Would be fine with me. Any other opinions @Kriesse @frontdevde?

**Comment by frontdevde** [comment]
lgtm. we should also add that top bar nicolas designed, so it's obvious to visitors that we're sold out

**Comment by verpixelt** [comment]
#86

**Comment by Lucie-H** [comment]
48bdb03873b2e11b627963a64a94956ba8a8a5d6

**Comment by usefulthink** [comment]
(PR is merged, closing this)
