### ISSUE TITLE
Finalize content on info page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#99]
@retrospekt @Lucie-H Can you review the info page and finalize it?
http://2015.cssconf.eu/info/

Feel free to move everything around, remove old stuff, add links to other pages, blog posts etc etc… let's make this page as useful as possible :)

New information that should be added:
- Closing Party (or Closing event?) will start right after the end of the schedule, takes place at Radialsystem
- There will be breakfast, lunch, dinner. All with veggie options.
- Maybe mention the hashtag #cssconfeu, add a link to lanyrd

**Comment by Lucie-H** [comment]
@Kriesse @retrospekt Hi! I have added some info to the infopage in a new branch. Maybe you could have a look before I open a PR? https://github.com/cssconf/2015.cssconf.eu/tree/info-page
